# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{AtomicTV}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Olly Legg"]
  s.date = %q{2011-06-01}
  s.description = %q{A command line tool to tag MP4 TV shows with metadata pulled from TheTVDB.com. It uses AtomicParsley to process the file.}
  s.email = %q{olly@51degrees.net}
  s.executables = ["AtomicTV"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "AtomicTV.gemspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/AtomicTV",
    "lib/AtomicTV.rb",
    "lib/AtomicTV/atomic_parsley_tagger.rb",
    "lib/AtomicTV/episode_metadata.rb",
    "lib/AtomicTV/filename_parser.rb",
    "lib/AtomicTV/tvdb_episode.rb",
    "spec/AtomicTV/atomic_parsley_tagger_spec.rb",
    "spec/AtomicTV/episode_metadata_spec.rb",
    "spec/AtomicTV/filename_parser_spec.rb",
    "spec/AtomicTV/tvdb_episode_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/olly/AtomicTV}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{A command line tool to tag MP4 TV shows with metadata pulled from TheTVDB.com.}
  s.test_files = [
    "spec/AtomicTV/atomic_parsley_tagger_spec.rb",
    "spec/AtomicTV/episode_metadata_spec.rb",
    "spec/AtomicTV/filename_parser_spec.rb",
    "spec/AtomicTV/tvdb_episode_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<plist>, ["= 3.1.0"])
      s.add_runtime_dependency(%q<tvdb_party>, ["= 0.6.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<webmock>, ["~> 1.6.2"])
    else
      s.add_dependency(%q<plist>, ["= 3.1.0"])
      s.add_dependency(%q<tvdb_party>, ["= 0.6.0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<webmock>, ["~> 1.6.2"])
    end
  else
    s.add_dependency(%q<plist>, ["= 3.1.0"])
    s.add_dependency(%q<tvdb_party>, ["= 0.6.0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<webmock>, ["~> 1.6.2"])
  end
end

